name: Deploy Backend

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 서버 접속 후 배포
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 52.78.194.14
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}

          script: |
            cd ~/backend
            git pull origin dev
            npm install
            npm run build
            pm2 restart app
